// this is javascript for content on the options page

var opts={initialValues:null,changes:null,init:function(){this.bg=chrome.extension.getBackgroundPage().bg;this.initialValues=this.bg.options;this.changes={};this.createUi()},createUi:function(){this.localize();this.createDialogButton();this.setEventListeners();this.setInitialValues();this.setPaneSwitcher()},localize:function(){var d=chrome.i18n.getMessage;document.title=d("opts_title");for(var a=document.querySelectorAll("*[data-i18n]"),c=0;c<a.length;c++){var b=a[c];b.textContent=d("opts_"+b.dataset.i18n)}document.getElementById("flattrButton").title=
d("opts_flattrButtonTooltip")},setPaneSwitcher:function(){var d=document.getElementById("labelContainer"),a=document.getElementById("contentPane");d.addEventListener("click",function(c){c=c.target;if("li"===c.tagName.toLowerCase()){for(var c=c.id.match(/^(.+)Label$/)[1],b=d.children,e=0;e<b.length;e++){var f=b[e];-1<f.id.search(c)?f.classList.add("paneLabelSelected"):f.classList.remove("paneLabelSelected")}b=a.children;for(e=0;e<b.length;e++)f=b[e],f.id===c?f.classList.add("paneSelected"):f.classList.remove("paneSelected")}},
!0)},setInitialValues:function(){var d=this.initialValues,a;for(a in d){var c=d[a],b;"boolean"===typeof c?(b=document.getElementById(a+(c?"Yes":"No")),b.checked=!0,b.addEventListener("change",this.onChange.bind(this)),b=document.getElementById(a+(c?"No":"Yes")),b.addEventListener("change",this.onChange.bind(this)),"ignoreDiacritics"===a&&!c&&(document.getElementById("unignoredDiacritics").disabled=!0,document.getElementById("unignoredDiacriticsFieldLabel").classList.add("disabledLabel"))):(b=document.getElementById(a),
c&&(b.value=c),b.addEventListener("input",this.onChange.bind(this)),("searchDelay"===a||"defaultParentId"===a)&&b.addEventListener("change",this.onChange.bind(this)))}},onChange:function(d){var a=d.target;if("radio"===a.type)key=a.name,value=/Yes$/.test(a.id);else{if("searchDelay"===a.id&&"change"===d.type&&!a.checkValidity()){alert(a.validationMessage);a.value=this.initialValues.searchDelay;return}key=a.id;value=a["searchDelay"===a.id?"valueAsNumber":"value"]}this.updateSaveButton(key,value)},updateSaveButton:function(d,
a){var c=!1;if(this.initialValues[d]===a)for(d in delete this.changes[d],this.changes){c=!0;break}else this.changes[d]=a,c=!0;var b=document.getElementById("searchDelay");document.getElementById("saveButton").disabled=!b.checkValidity()||!c},setEventListeners:function(){for(var d=document.getElementsByName("ignoreDiacritics"),a=document.getElementById("unignoredDiacritics"),c=document.getElementById("unignoredDiacriticsFieldLabel"),b=0;b<d.length;b++)d[b].addEventListener("change",function(b){b=/Yes$/.test(b.target.id);
a.disabled=!b;c.classList[b?"remove":"add"]("disabledLabel")});var e=this;document.getElementById("saveButton").addEventListener("click",function(a){var b=e.changes;e.bg.updateOptions(b);for(var c in b)e.initialValues[c]=b[c];a.target.disabled=!0});var f=document.getElementById("reindexButton");f.addEventListener("click",function(){e.bg.tagStore.createIndex();f.disabled=!0})},createDialogButton:function(){var d=this.bg.tagStore,a=chrome.i18n.getMessage,c=this.initialValues.defaultParentId,b=document.getElementById("defaultParentTitle");
b.textContent=d.getName(c,!0);b.title=a("opts_defaultParentIdTooltip");d=document.getElementById("dialogButton");d.textContent=a("opts_dialogButtonLabel");d.addEventListener("click",this.openDialog.bind(this))},dialogCreated:!1,openDialog:function(){this.dialogCreated?(this.tagTree.refresh(),$("#dialog").dialog("open")):this.createDialog()},createDialog:function(){var d=this,a=chrome.i18n.getMessage,c=document.getElementById("defaultParentId"),b=document.getElementById("defaultParentTitle"),e=this.tagTree=
new TagTree({store:this.bg.tagStore,options:this.bg.options,externalSelector:{getSelected:function(){return[defaultParentId.value]}},multiple:!1},"tagTree");e.on("tagtree-check",function(a,g){c.value=g.id;b.textContent=e.store.getName(g.id,!0);d.updateSaveButton("defaultParentId",g.id)});e.on("tagtree-rename",function(a,c){b.textContent=e.store.getName(c.id,!0)});$("#dialog").dialog({autoOpen:!1,buttons:[{text:a("opts_dialogCloseButtonLabel"),click:function(){$(this).dialog("close")}}],modal:!0,width:300,
title:a("opts_defaultParentIdFieldLabel")});$("#dialog").dialog("open");this.dialogCreated=!0}};$(function(){opts.init()});
